import { TrpcProvider } from "@/utils/trpc-provider";

import "@/styles/reset.css";
import "@/styles/globals.css";

export const metadata = {
  title: "IT Hub | Github Profile Analytics",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  );
}

export default RootLayout;
