import { TrpcProvider } from "@/utils/trpc-provider";

import "@/styles/reset.css";
import "@/styles/globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { className } from "@/utils/font";

export const metadata = {
  title: "IT Hub | Github Profile Analytics",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={className}>
        <TrpcProvider>
          <div className="flex max-w-6xl mx-auto flex-col items-center justify-center py-2 min-h-screen">
            <Header />
            <div className="flex flex-1 w-full flex-col items-center justify-center text-center px-4 sm:py-28 py-20">
              {children}
            </div>
            <Footer />
          </div>
        </TrpcProvider>
      </body>
    </html>
  );
}

export default RootLayout;
